"""
Script para adicionar 5 alunos de teste com todas as informações
para verificar funcionalidade do sistema e duplicação de cadastros
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from data_manager import DataManager

def add_test_students():
    """Adiciona 5 alunos de teste com todas as informações"""
    dm = DataManager()
    
    # Dados dos 5 alunos de teste
    test_students = [
        {
            'cadastro': {
                'nome_completo': 'Ana Carolina Silva Santos',
                'data_nascimento': '2009-03-15',
                'cpf': '123.456.789-01',
                'rg': '1234567-1',
                'nome_mae': 'Maria Silva Santos',
                'nome_pai': 'José Carlos Santos',
                'telefone': '(85) 98765-4321',
                'email': 'ana.silva@email.com',
                'endereco': 'Rua das Flores',
                'numero': '123',
                'complemento': 'Apto 201',
                'bairro': 'Centro',
                'cidade': 'Fortaleza',
                'uf': 'CE',
                'cep': '60000-100',
                'escola_origem': 'Escola Municipal José de Alencar',
                'ano_escolar': '9º Ano',
                'turno': 'Matutino',
                'status': 'Ativo'
            },
            'pei': {
                'necessidade_especial': 'Não',
                'tipo_deficiencia': '',
                'laudo_medico': 'Não',
                'data_laudo': '',
                'cid': '',
                'medicacao': '',
                'restricoes': '',
                'apoio_necessario': '',
                'adaptacao_curricular': '',
                'acompanhamento_especializado': '',
                'recursos_necessarios': '',
                'observacoes': ''
            },
            'socioeconomico': {
                'renda_familiar': 'De 2 a 3 salários mínimos',
                'qtd_pessoas_casa': 4,
                'tipo_moradia': 'Própria',
                'possui_internet': 'Sim',
                'possui_computador': 'Sim',
                'possui_smartphone': 'Sim',
                'bolsa_familia': 'Não',
                'auxilio_brasil': 'Não',
                'beneficio_social': 'Não',
                'situacao_trabalho_responsavel': 'Empregado com carteira assinada',
                'profissao_responsavel': 'Vendedor',
                'escolaridade_mae': 'Médio Completo',
                'escolaridade_pai': 'Médio Completo',
                'transporte_escolar': 'Não',
                'tempo_deslocamento': 'De 15 a 30 minutos'
            },
            'questionario_saeb': {
                'sexo': 'Feminino',
                'idade': '15 anos',
                'lingua_familia': 'Português',
                'cor_raca': 'Parda',
                'deficiencia': 'Não',
                'tea': 'Não',
                'altas_habilidades': 'Não',
                'mora_mae': 'Sim',
                'mora_pai': 'Sim',
                'mora_avo': 'Não',
                'mora_avoh': 'Não',
                'mora_outros': 'Não',
                'escolaridade_mae': 'Médio completo',
                'escolaridade_pai': 'Médio completo',
                'responsavel_le': 'De vez em quando',
                'responsavel_conversa': 'Sempre / quase sempre',
                'responsavel_incentiva_estudar': 'Sempre / quase sempre',
                'responsavel_incentiva_tarefas': 'Sempre / quase sempre',
                'responsavel_incentiva_aulas': 'Sempre / quase sempre',
                'responsavel_participa_reunioes': 'De vez em quando',
                'bairro_asfalto': 'Sim',
                'bairro_agua_tratada': 'Sim',
                'bairro_iluminacao': 'Sim',
                'qtd_geladeira': '1',
                'qtd_computador': '1',
                'qtd_quartos': '2',
                'qtd_televisao': '2',
                'qtd_banheiro': '1',
                'qtd_carro': 'Nenhum',
                'qtd_celular_internet': '3 ou mais',
                'casa_tv_internet': 'Sim',
                'casa_wifi': 'Sim',
                'casa_mesa_estudar': 'Sim',
                'casa_microondas': 'Sim',
                'casa_aspirador': 'Não',
                'casa_maquina_lavar': 'Sim',
                'casa_freezer': 'Não',
                'casa_garagem': 'Não',
                'tempo_escola': 'Menos de 30 minutos',
                'transporte_gratuito': 'Não',
                'passe_escolar': 'Sim',
                'meio_transporte_principal': 'Ônibus',
                'idade_entrada_escola': '6–7 anos',
                'trajetoria_educacao': 'Sempre escola pública',
                'reprovacao': 'Nunca',
                'abandono': 'Nunca',
                'tempo_estudar': 'Entre 1–2h',
                'tempo_extracurriculares': 'Menos de 1h',
                'tempo_trabalho_domestico': 'Menos de 1h',
                'tempo_trabalho_remunerado': 'Não uso meu tempo para isso',
                'tempo_lazer': 'Entre 1–2h',
                'prof_explica': 'A maioria',
                'prof_pergunta': 'A maioria',
                'prof_debate': 'Poucos',
                'prof_grupos': 'A maioria',
                'prof_bullying': 'A maioria',
                'prof_racismo': 'Poucos',
                'prof_genero': 'A maioria',
                'escola_interesse': 'Concordo',
                'escola_motivacao': 'Concordo',
                'escola_opinioes': 'Concordo',
                'escola_seguranca': 'Concordo',
                'escola_vontade_prof': 'Concordo totalmente',
                'escola_dificuldade': 'Concordo',
                'escola_avaliacoes': 'Concordo',
                'escola_prof_acreditam': 'Concordo totalmente',
                'escola_motivacao_continuar': 'Concordo totalmente',
                'expectativa_futura': 'Continuar estudando'
            },
            'saude': {
                'tipo_sanguineo': 'O',
                'fator_rh': 'Positivo',
                'alergias': 'Nenhuma alergia conhecida',
                'doencas_cronicas': 'Não',
                'medicamentos_uso_continuo': 'Não',
                'historico_doencas': 'Saudável',
                'vacinacao_em_dia': 'Sim',
                'plano_saude': 'Não',
                'nome_plano_saude': '',
                'numero_plano': '',
                'contato_emergencia': 'Maria Silva Santos',
                'telefone_emergencia': '(85) 98765-4321',
                'parentesco_emergencia': 'Mãe',
                'observacoes_saude': 'Nenhuma observação especial'
            }
        },
        {
            'cadastro': {
                'nome_completo': 'Pedro Henrique Oliveira Costa',
                'data_nascimento': '2010-07-22',
                'cpf': '234.567.890-12',
                'rg': '2345678-2',
                'nome_mae': 'Carla Oliveira Costa',
                'nome_pai': 'Henrique Costa',
                'telefone': '(85) 99876-5432',
                'email': 'pedro.oliveira@email.com',
                'endereco': 'Avenida Beira Mar',
                'numero': '456',
                'complemento': 'Casa',
                'bairro': 'Meireles',
                'cidade': 'Fortaleza',
                'uf': 'CE',
                'cep': '60165-121',
                'escola_origem': 'Colégio Estadual Dom Pedro II',
                'ano_escolar': '8º Ano',
                'turno': 'Vespertino',
                'status': 'Ativo'
            },
            'pei': {
                'necessidade_especial': 'Sim',
                'tipo_deficiencia': 'Transtorno do Espectro Autista (TEA)',
                'laudo_medico': 'Sim',
                'data_laudo': '2020-03-10',
                'cid': 'F84.0',
                'medicacao': 'Risperidona 1mg - 1x ao dia',
                'restricoes': 'Evitar ambientes muito barulhentos',
                'apoio_necessario': 'Professor de Apoio, Sala de Recursos Multifuncionais',
                'adaptacao_curricular': 'Tempo estendido para provas, instruções visuais, atividades estruturadas',
                'acompanhamento_especializado': 'Terapia Ocupacional semanal, Psicologia mensal',
                'recursos_necessarios': 'Material visual, agenda estruturada, fones de ouvido',
                'observacoes': 'Aluno com bom desenvolvimento cognitivo, necessita de rotina previsível'
            },
            'socioeconomico': {
                'renda_familiar': 'De 3 a 5 salários mínimos',
                'qtd_pessoas_casa': 3,
                'tipo_moradia': 'Própria',
                'possui_internet': 'Sim',
                'possui_computador': 'Sim',
                'possui_smartphone': 'Sim',
                'bolsa_familia': 'Não',
                'auxilio_brasil': 'Não',
                'beneficio_social': 'Não',
                'situacao_trabalho_responsavel': 'Funcionário público',
                'profissao_responsavel': 'Professora',
                'escolaridade_mae': 'Superior Completo',
                'escolaridade_pai': 'Superior Completo',
                'transporte_escolar': 'Não',
                'tempo_deslocamento': 'Até 15 minutos'
            },
            'questionario_saeb': {
                'sexo': 'Masculino',
                'idade': '14 anos',
                'lingua_familia': 'Português',
                'cor_raca': 'Branca',
                'deficiencia': 'Sim',
                'tea': 'Sim',
                'altas_habilidades': 'Não',
                'mora_mae': 'Sim',
                'mora_pai': 'Sim',
                'mora_avo': 'Não',
                'mora_avoh': 'Não',
                'mora_outros': 'Não',
                'escolaridade_mae': 'Superior completo',
                'escolaridade_pai': 'Superior completo',
                'responsavel_le': 'Sempre / quase sempre',
                'responsavel_conversa': 'Sempre / quase sempre',
                'responsavel_incentiva_estudar': 'Sempre / quase sempre',
                'responsavel_incentiva_tarefas': 'Sempre / quase sempre',
                'responsavel_incentiva_aulas': 'Sempre / quase sempre',
                'responsavel_participa_reunioes': 'Sempre / quase sempre',
                'bairro_asfalto': 'Sim',
                'bairro_agua_tratada': 'Sim',
                'bairro_iluminacao': 'Sim',
                'qtd_geladeira': '1',
                'qtd_computador': '2',
                'qtd_quartos': '3 ou mais',
                'qtd_televisao': '2',
                'qtd_banheiro': '2',
                'qtd_carro': '1',
                'qtd_celular_internet': '3 ou mais',
                'casa_tv_internet': 'Sim',
                'casa_wifi': 'Sim',
                'casa_mesa_estudar': 'Sim',
                'casa_microondas': 'Sim',
                'casa_aspirador': 'Sim',
                'casa_maquina_lavar': 'Sim',
                'casa_freezer': 'Não',
                'casa_garagem': 'Sim',
                'tempo_escola': 'Menos de 30 minutos',
                'transporte_gratuito': 'Não',
                'passe_escolar': 'Não',
                'meio_transporte_principal': 'Carro',
                'idade_entrada_escola': '4–5 anos',
                'trajetoria_educacao': 'Sempre escola pública',
                'reprovacao': 'Nunca',
                'abandono': 'Nunca',
                'tempo_estudar': 'Mais de 2h',
                'tempo_extracurriculares': 'Entre 1–2h',
                'tempo_trabalho_domestico': 'Não uso meu tempo para isso',
                'tempo_trabalho_remunerado': 'Não uso meu tempo para isso',
                'tempo_lazer': 'Entre 1–2h',
                'prof_explica': 'Todos',
                'prof_pergunta': 'A maioria',
                'prof_debate': 'A maioria',
                'prof_grupos': 'A maioria',
                'prof_bullying': 'Todos',
                'prof_racismo': 'Todos',
                'prof_genero': 'Todos',
                'escola_interesse': 'Concordo totalmente',
                'escola_motivacao': 'Concordo totalmente',
                'escola_opinioes': 'Concordo',
                'escola_seguranca': 'Concordo totalmente',
                'escola_vontade_prof': 'Concordo totalmente',
                'escola_dificuldade': 'Discordo',
                'escola_avaliacoes': 'Concordo',
                'escola_prof_acreditam': 'Concordo totalmente',
                'escola_motivacao_continuar': 'Concordo totalmente',
                'expectativa_futura': 'Continuar estudando'
            },
            'saude': {
                'tipo_sanguineo': 'A',
                'fator_rh': 'Positivo',
                'alergias': 'Alergia a camarão',
                'doencas_cronicas': 'Transtorno do Espectro Autista',
                'medicamentos_uso_continuo': 'Risperidona 1mg',
                'historico_doencas': 'Diagnóstico de TEA aos 3 anos',
                'vacinacao_em_dia': 'Sim',
                'plano_saude': 'Sim',
                'nome_plano_saude': 'Unimed',
                'numero_plano': '12345678901',
                'contato_emergencia': 'Carla Oliveira Costa',
                'telefone_emergencia': '(85) 99876-5432',
                'parentesco_emergencia': 'Mãe',
                'observacoes_saude': 'Acompanhamento psiquiátrico mensal'
            }
        },
        {
            'cadastro': {
                'nome_completo': 'Juliana Rodrigues Lima',
                'data_nascimento': '2008-11-30',
                'cpf': '345.678.901-23',
                'rg': '3456789-3',
                'nome_mae': 'Sandra Rodrigues Lima',
                'nome_pai': 'Ricardo Lima',
                'telefone': '(85) 98123-4567',
                'email': 'juliana.lima@email.com',
                'endereco': 'Rua do Comércio',
                'numero': '789',
                'complemento': '',
                'bairro': 'Aldeota',
                'cidade': 'Fortaleza',
                'uf': 'CE',
                'cep': '60150-160',
                'escola_origem': 'Escola Estadual Paulo Freire',
                'ano_escolar': '9º Ano',
                'turno': 'Matutino',
                'status': 'Ativo'
            },
            'pei': {
                'necessidade_especial': 'Sim',
                'tipo_deficiencia': 'Altas Habilidades/Superdotação',
                'laudo_medico': 'Sim',
                'data_laudo': '2021-06-15',
                'cid': 'Z55',
                'medicacao': '',
                'restricoes': '',
                'apoio_necessario': 'Enriquecimento curricular, Atividades desafiadoras',
                'adaptacao_curricular': 'Currículo enriquecido com atividades avançadas, projetos de pesquisa',
                'acompanhamento_especializado': 'Orientação psicopedagógica',
                'recursos_necessarios': 'Acesso a biblioteca ampliada, materiais de pesquisa',
                'observacoes': 'Aluna com alta capacidade em Matemática e Ciências'
            },
            'socioeconomico': {
                'renda_familiar': 'De 5 a 10 salários mínimos',
                'qtd_pessoas_casa': 4,
                'tipo_moradia': 'Própria',
                'possui_internet': 'Sim',
                'possui_computador': 'Sim',
                'possui_smartphone': 'Sim',
                'bolsa_familia': 'Não',
                'auxilio_brasil': 'Não',
                'beneficio_social': 'Não',
                'situacao_trabalho_responsavel': 'Empresário',
                'profissao_responsavel': 'Comerciante',
                'escolaridade_mae': 'Superior Completo',
                'escolaridade_pai': 'Médio Completo',
                'transporte_escolar': 'Não',
                'tempo_deslocamento': 'De 15 a 30 minutos'
            },
            'questionario_saeb': {
                'sexo': 'Feminino',
                'idade': '16 anos',
                'lingua_familia': 'Português',
                'cor_raca': 'Branca',
                'deficiencia': 'Não',
                'tea': 'Não',
                'altas_habilidades': 'Sim',
                'mora_mae': 'Sim',
                'mora_pai': 'Sim',
                'mora_avo': 'Não',
                'mora_avoh': 'Não',
                'mora_outros': 'Sim',
                'escolaridade_mae': 'Superior completo',
                'escolaridade_pai': 'Médio completo',
                'responsavel_le': 'Sempre / quase sempre',
                'responsavel_conversa': 'Sempre / quase sempre',
                'responsavel_incentiva_estudar': 'Sempre / quase sempre',
                'responsavel_incentiva_tarefas': 'Sempre / quase sempre',
                'responsavel_incentiva_aulas': 'Sempre / quase sempre',
                'responsavel_participa_reunioes': 'Sempre / quase sempre',
                'bairro_asfalto': 'Sim',
                'bairro_agua_tratada': 'Sim',
                'bairro_iluminacao': 'Sim',
                'qtd_geladeira': '1',
                'qtd_computador': '2',
                'qtd_quartos': '3 ou mais',
                'qtd_televisao': '3 ou mais',
                'qtd_banheiro': '2',
                'qtd_carro': '2',
                'qtd_celular_internet': '3 ou mais',
                'casa_tv_internet': 'Sim',
                'casa_wifi': 'Sim',
                'casa_mesa_estudar': 'Sim',
                'casa_microondas': 'Sim',
                'casa_aspirador': 'Sim',
                'casa_maquina_lavar': 'Sim',
                'casa_freezer': 'Sim',
                'casa_garagem': 'Sim',
                'tempo_escola': 'Menos de 30 minutos',
                'transporte_gratuito': 'Não',
                'passe_escolar': 'Não',
                'meio_transporte_principal': 'Carro',
                'idade_entrada_escola': '4–5 anos',
                'trajetoria_educacao': 'Ambas',
                'reprovacao': 'Nunca',
                'abandono': 'Nunca',
                'tempo_estudar': 'Mais de 2h',
                'tempo_extracurriculares': 'Mais de 2h',
                'tempo_trabalho_domestico': 'Menos de 1h',
                'tempo_trabalho_remunerado': 'Não uso meu tempo para isso',
                'tempo_lazer': 'Entre 1–2h',
                'prof_explica': 'Todos',
                'prof_pergunta': 'Todos',
                'prof_debate': 'Todos',
                'prof_grupos': 'A maioria',
                'prof_bullying': 'A maioria',
                'prof_racismo': 'A maioria',
                'prof_genero': 'A maioria',
                'escola_interesse': 'Concordo totalmente',
                'escola_motivacao': 'Concordo totalmente',
                'escola_opinioes': 'Concordo totalmente',
                'escola_seguranca': 'Concordo totalmente',
                'escola_vontade_prof': 'Concordo totalmente',
                'escola_dificuldade': 'Discordo totalmente',
                'escola_avaliacoes': 'Concordo',
                'escola_prof_acreditam': 'Concordo totalmente',
                'escola_motivacao_continuar': 'Concordo totalmente',
                'expectativa_futura': 'Continuar estudando'
            },
            'saude': {
                'tipo_sanguineo': 'B',
                'fator_rh': 'Positivo',
                'alergias': 'Nenhuma',
                'doencas_cronicas': 'Não',
                'medicamentos_uso_continuo': 'Não',
                'historico_doencas': 'Saudável',
                'vacinacao_em_dia': 'Sim',
                'plano_saude': 'Sim',
                'nome_plano_saude': 'Bradesco Saúde',
                'numero_plano': '98765432100',
                'contato_emergencia': 'Sandra Rodrigues Lima',
                'telefone_emergencia': '(85) 98123-4567',
                'parentesco_emergencia': 'Mãe',
                'observacoes_saude': 'Nenhuma observação'
            }
        },
        {
            'cadastro': {
                'nome_completo': 'Lucas Ferreira Souza',
                'data_nascimento': '2009-05-18',
                'cpf': '456.789.012-34',
                'rg': '4567890-4',
                'nome_mae': 'Fernanda Ferreira Souza',
                'nome_pai': 'Roberto Souza',
                'telefone': '(85) 97234-5678',
                'email': 'lucas.souza@email.com',
                'endereco': 'Travessa São José',
                'numero': '321',
                'complemento': 'Fundos',
                'bairro': 'Messejana',
                'cidade': 'Fortaleza',
                'uf': 'CE',
                'cep': '60841-000',
                'escola_origem': 'Escola Municipal Anísio Teixeira',
                'ano_escolar': '9º Ano',
                'turno': 'Vespertino',
                'status': 'Ativo'
            },
            'pei': {
                'necessidade_especial': 'Não',
                'tipo_deficiencia': '',
                'laudo_medico': 'Não',
                'data_laudo': '',
                'cid': '',
                'medicacao': '',
                'restricoes': '',
                'apoio_necessario': '',
                'adaptacao_curricular': '',
                'acompanhamento_especializado': '',
                'recursos_necessarios': '',
                'observacoes': ''
            },
            'socioeconomico': {
                'renda_familiar': 'De 1 a 2 salários mínimos',
                'qtd_pessoas_casa': 5,
                'tipo_moradia': 'Alugada',
                'possui_internet': 'Sim',
                'possui_computador': 'Não',
                'possui_smartphone': 'Sim',
                'bolsa_familia': 'Sim',
                'auxilio_brasil': 'Não',
                'beneficio_social': 'Não',
                'situacao_trabalho_responsavel': 'Autônomo',
                'profissao_responsavel': 'Diarista',
                'escolaridade_mae': 'Fundamental Completo',
                'escolaridade_pai': 'Fundamental Incompleto',
                'transporte_escolar': 'Sim - Municipal',
                'tempo_deslocamento': 'De 30 a 60 minutos'
            },
            'questionario_saeb': {
                'sexo': 'Masculino',
                'idade': '15 anos',
                'lingua_familia': 'Português',
                'cor_raca': 'Preta',
                'deficiencia': 'Não',
                'tea': 'Não',
                'altas_habilidades': 'Não',
                'mora_mae': 'Sim',
                'mora_pai': 'Não',
                'mora_avo': 'Sim',
                'mora_avoh': 'Não',
                'mora_outros': 'Sim',
                'escolaridade_mae': 'Fundamental completo',
                'escolaridade_pai': 'Fundamental incompleto',
                'responsavel_le': 'Nunca / quase nunca',
                'responsavel_conversa': 'De vez em quando',
                'responsavel_incentiva_estudar': 'De vez em quando',
                'responsavel_incentiva_tarefas': 'De vez em quando',
                'responsavel_incentiva_aulas': 'Sempre / quase sempre',
                'responsavel_participa_reunioes': 'Nunca / quase nunca',
                'bairro_asfalto': 'Sim',
                'bairro_agua_tratada': 'Sim',
                'bairro_iluminacao': 'Não',
                'qtd_geladeira': '1',
                'qtd_computador': 'Nenhum',
                'qtd_quartos': '2',
                'qtd_televisao': '1',
                'qtd_banheiro': '1',
                'qtd_carro': 'Nenhum',
                'qtd_celular_internet': '2',
                'casa_tv_internet': 'Não',
                'casa_wifi': 'Sim',
                'casa_mesa_estudar': 'Não',
                'casa_microondas': 'Não',
                'casa_aspirador': 'Não',
                'casa_maquina_lavar': 'Não',
                'casa_freezer': 'Não',
                'casa_garagem': 'Não',
                'tempo_escola': 'Entre 30 min e 1 hora',
                'transporte_gratuito': 'Sim',
                'passe_escolar': 'Sim',
                'meio_transporte_principal': 'Ônibus',
                'idade_entrada_escola': '6–7 anos',
                'trajetoria_educacao': 'Sempre escola pública',
                'reprovacao': 'Uma vez',
                'abandono': 'Nunca',
                'tempo_estudar': 'Menos de 1h',
                'tempo_extracurriculares': 'Não uso meu tempo para isso',
                'tempo_trabalho_domestico': 'Entre 1–2h',
                'tempo_trabalho_remunerado': 'Menos de 1h',
                'tempo_lazer': 'Mais de 2h',
                'prof_explica': 'A maioria',
                'prof_pergunta': 'Poucos',
                'prof_debate': 'Poucos',
                'prof_grupos': 'Poucos',
                'prof_bullying': 'Poucos',
                'prof_racismo': 'Poucos',
                'prof_genero': 'Poucos',
                'escola_interesse': 'Discordo',
                'escola_motivacao': 'Discordo',
                'escola_opinioes': 'Discordo',
                'escola_seguranca': 'Concordo',
                'escola_vontade_prof': 'Concordo',
                'escola_dificuldade': 'Concordo totalmente',
                'escola_avaliacoes': 'Concordo',
                'escola_prof_acreditam': 'Concordo',
                'escola_motivacao_continuar': 'Concordo',
                'expectativa_futura': 'Trabalhar e estudar'
            },
            'saude': {
                'tipo_sanguineo': 'O',
                'fator_rh': 'Positivo',
                'alergias': 'Nenhuma',
                'doencas_cronicas': 'Não',
                'medicamentos_uso_continuo': 'Não',
                'historico_doencas': 'Saudável',
                'vacinacao_em_dia': 'Sim',
                'plano_saude': 'Não',
                'nome_plano_saude': '',
                'numero_plano': '',
                'contato_emergencia': 'Fernanda Ferreira Souza',
                'telefone_emergencia': '(85) 97234-5678',
                'parentesco_emergencia': 'Mãe',
                'observacoes_saude': 'Nenhuma'
            }
        },
        {
            'cadastro': {
                'nome_completo': 'Mariana Alves Pereira',
                'data_nascimento': '2010-09-08',
                'cpf': '567.890.123-45',
                'rg': '5678901-5',
                'nome_mae': 'Patricia Alves Pereira',
                'nome_pai': 'João Pereira',
                'telefone': '(85) 96345-6789',
                'email': 'mariana.pereira@email.com',
                'endereco': 'Rua das Palmeiras',
                'numero': '654',
                'complemento': 'Casa 2',
                'bairro': 'Parangaba',
                'cidade': 'Fortaleza',
                'uf': 'CE',
                'cep': '60740-000',
                'escola_origem': 'Escola Municipal Castro Alves',
                'ano_escolar': '8º Ano',
                'turno': 'Matutino',
                'status': 'Ativo'
            },
            'pei': {
                'necessidade_especial': 'Sim',
                'tipo_deficiencia': 'Deficiência Auditiva',
                'laudo_medico': 'Sim',
                'data_laudo': '2019-11-20',
                'cid': 'H90.3',
                'medicacao': '',
                'restricoes': 'Necessita sentar nas primeiras carteiras',
                'apoio_necessario': 'Intérprete de Libras, Tecnologias Assistivas',
                'adaptacao_curricular': 'Material visual, legendas em vídeos, intérprete de Libras',
                'acompanhamento_especializado': 'Fonoaudiologia semanal',
                'recursos_necessarios': 'Aparelho auditivo, materiais visuais',
                'observacoes': 'Aluna com perda auditiva bilateral, usa aparelho auditivo'
            },
            'socioeconomico': {
                'renda_familiar': 'De 2 a 3 salários mínimos',
                'qtd_pessoas_casa': 4,
                'tipo_moradia': 'Financiada',
                'possui_internet': 'Sim',
                'possui_computador': 'Sim',
                'possui_smartphone': 'Sim',
                'bolsa_familia': 'Não',
                'auxilio_brasil': 'Não',
                'beneficio_social': 'Sim',
                'situacao_trabalho_responsavel': 'Empregado com carteira assinada',
                'profissao_responsavel': 'Auxiliar administrativo',
                'escolaridade_mae': 'Médio Completo',
                'escolaridade_pai': 'Médio Incompleto',
                'transporte_escolar': 'Sim - Municipal',
                'tempo_deslocamento': 'De 30 a 60 minutos'
            },
            'questionario_saeb': {
                'sexo': 'Feminino',
                'idade': '14 anos',
                'lingua_familia': 'Libras / Línguas de sinais',
                'cor_raca': 'Parda',
                'deficiencia': 'Sim',
                'tea': 'Não',
                'altas_habilidades': 'Não',
                'mora_mae': 'Sim',
                'mora_pai': 'Sim',
                'mora_avo': 'Não',
                'mora_avoh': 'Não',
                'mora_outros': 'Sim',
                'escolaridade_mae': 'Médio completo',
                'escolaridade_pai': 'Fundamental incompleto',
                'responsavel_le': 'De vez em quando',
                'responsavel_conversa': 'Sempre / quase sempre',
                'responsavel_incentiva_estudar': 'Sempre / quase sempre',
                'responsavel_incentiva_tarefas': 'Sempre / quase sempre',
                'responsavel_incentiva_aulas': 'Sempre / quase sempre',
                'responsavel_participa_reunioes': 'Sempre / quase sempre',
                'bairro_asfalto': 'Sim',
                'bairro_agua_tratada': 'Sim',
                'bairro_iluminacao': 'Sim',
                'qtd_geladeira': '1',
                'qtd_computador': '1',
                'qtd_quartos': '2',
                'qtd_televisao': '1',
                'qtd_banheiro': '1',
                'qtd_carro': 'Nenhum',
                'qtd_celular_internet': '2',
                'casa_tv_internet': 'Sim',
                'casa_wifi': 'Sim',
                'casa_mesa_estudar': 'Sim',
                'casa_microondas': 'Sim',
                'casa_aspirador': 'Não',
                'casa_maquina_lavar': 'Sim',
                'casa_freezer': 'Não',
                'casa_garagem': 'Não',
                'tempo_escola': 'Entre 30 min e 1 hora',
                'transporte_gratuito': 'Sim',
                'passe_escolar': 'Sim',
                'meio_transporte_principal': 'Ônibus',
                'idade_entrada_escola': '6–7 anos',
                'trajetoria_educacao': 'Sempre escola pública',
                'reprovacao': 'Nunca',
                'abandono': 'Nunca',
                'tempo_estudar': 'Entre 1–2h',
                'tempo_extracurriculares': 'Menos de 1h',
                'tempo_trabalho_domestico': 'Menos de 1h',
                'tempo_trabalho_remunerado': 'Não uso meu tempo para isso',
                'tempo_lazer': 'Entre 1–2h',
                'prof_explica': 'A maioria',
                'prof_pergunta': 'A maioria',
                'prof_debate': 'Poucos',
                'prof_grupos': 'A maioria',
                'prof_bullying': 'A maioria',
                'prof_racismo': 'A maioria',
                'prof_genero': 'A maioria',
                'escola_interesse': 'Concordo',
                'escola_motivacao': 'Concordo',
                'escola_opinioes': 'Concordo',
                'escola_seguranca': 'Concordo',
                'escola_vontade_prof': 'Concordo totalmente',
                'escola_dificuldade': 'Concordo',
                'escola_avaliacoes': 'Concordo',
                'escola_prof_acreditam': 'Concordo totalmente',
                'escola_motivacao_continuar': 'Concordo totalmente',
                'expectativa_futura': 'Continuar estudando'
            },
            'saude': {
                'tipo_sanguineo': 'AB',
                'fator_rh': 'Positivo',
                'alergias': 'Alergia a poeira',
                'doencas_cronicas': 'Perda auditiva bilateral',
                'medicamentos_uso_continuo': 'Não',
                'historico_doencas': 'Perda auditiva desde nascimento',
                'vacinacao_em_dia': 'Sim',
                'plano_saude': 'Sim',
                'nome_plano_saude': 'Hapvida',
                'numero_plano': '55667788990',
                'contato_emergencia': 'Patricia Alves Pereira',
                'telefone_emergencia': '(85) 96345-6789',
                'parentesco_emergencia': 'Mãe',
                'observacoes_saude': 'Usa aparelho auditivo bilateral'
            }
        }
    ]
    
    print("=" * 60)
    print("ADICIONANDO 5 ALUNOS DE TESTE")
    print("=" * 60)
    
    alunos_ids = []
    
    for i, student in enumerate(test_students, 1):
        print(f"\nAdicionando aluno {i}/5: {student['cadastro']['nome_completo']}")
        
        # Adicionar cadastro
        aluno_id = dm.add_record('cadastro', student['cadastro'])
        alunos_ids.append(aluno_id)
        print(f"  ✓ Cadastro criado - ID: {aluno_id}")
        
        # Adicionar PEI
        student['pei']['aluno_id'] = aluno_id
        dm.add_record('pei', student['pei'])
        print(f"  ✓ PEI cadastrado")
        
        # Adicionar socioeconômico
        student['socioeconomico']['aluno_id'] = aluno_id
        dm.add_record('socioeconomico', student['socioeconomico'])
        print(f"  ✓ Socioeconômico cadastrado")
        
        # Adicionar questionário SAEB
        student['questionario_saeb']['aluno_id'] = aluno_id
        dm.add_record('questionario_saeb', student['questionario_saeb'])
        print(f"  ✓ Questionário SAEB cadastrado")
        
        # Adicionar saúde
        student['saude']['aluno_id'] = aluno_id
        dm.add_record('saude', student['saude'])
        print(f"  ✓ Saúde cadastrada")
    
    print("\n" + "=" * 60)
    print("✅ TODOS OS 5 ALUNOS FORAM ADICIONADOS COM SUCESSO!")
    print("=" * 60)
    print("\nIDs dos alunos criados:", alunos_ids)
    
    # Verificar dados
    df_cadastro = dm.get_data('cadastro')
    print(f"\nTotal de alunos no sistema: {len(df_cadastro)}")
    
    # Verificar duplicidades
    print("\n" + "=" * 60)
    print("VERIFICAÇÃO DE DUPLICIDADE")
    print("=" * 60)
    
    duplicados = df_cadastro[df_cadastro.duplicated(subset=['cpf'], keep=False)]
    if len(duplicados) > 0:
        print("⚠️  DUPLICIDADES ENCONTRADAS:")
        print(duplicados[['id', 'nome_completo', 'cpf']])
    else:
        print("✅ Nenhuma duplicidade encontrada por CPF")
    
    duplicados_nome = df_cadastro[df_cadastro.duplicated(subset=['nome_completo'], keep=False)]
    if len(duplicados_nome) > 0:
        print("\n⚠️  DUPLICIDADES ENCONTRADAS POR NOME:")
        print(duplicados_nome[['id', 'nome_completo']])
    else:
        print("✅ Nenhuma duplicidade encontrada por Nome")

if __name__ == "__main__":
    add_test_students()
